apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotter-cr
rules:
  - apiGroups:
      - hardik.dev
    resources:
      - snapshotters
    verbs:
      - list
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
