apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snapshotter-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snapshotter-cr
subjects:
  - kind: ServiceAccount
    name: snapshotter-sa
    namespace: default
